services:
  ottoexcel_db:
    image: postgres:15
    container_name: ottoexcel_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ottoexcel_bot:
    image: ${DOCKER_IMAGE:-ghcr.io/liraa97/ottoexcel:latest}
    container_name: ottoexcel_bot
    env_file:
      - .env
    restart: always
    depends_on:
      ottoexcel_db:
        condition: service_healthy

volumes:
  postgres_data: 